-- Generated by herdr. Edit the source theme instead.
vim.o.termguicolors = true
vim.o.background = 'dark'
vim.g.colors_name = 'herdr'
local hi = vim.api.nvim_set_hl
local C = {
  bg = '#0a0a0a', surface = '#0f0f0f', fg = '#ffffff', muted = '#888888',
  accent = '#d24747', red = '#dc2626',
  green = '#49d36d', yellow = '#f59e0b',
  blue = '#3b82f6', purple = '#8350d8',
  cyan = '#22d3ee', comment = '#6b9fb5',
  border = '#1a1a1a', dim = '#555555', selection = '#0f0f0f'
}
hi(0, 'Normal', { fg = C.fg, bg = C.bg })
hi(0, 'NormalNC', { fg = C.fg, bg = C.bg })
hi(0, 'NormalFloat', { fg = C.fg, bg = C.surface })
hi(0, 'FloatBorder', { fg = C.accent, bg = C.surface })
hi(0, 'WinSeparator', { fg = C.border })
hi(0, 'LineNr', { fg = C.muted, bg = C.bg })
hi(0, 'CursorLine', { bg = C.surface })
hi(0, 'CursorLineNr', { fg = C.accent, bold = true })
hi(0, 'StatusLine', { fg = C.fg, bg = C.surface })
hi(0, 'StatusLineNC', { fg = C.muted, bg = C.surface })
hi(0, 'Visual', { bg = C.selection })
hi(0, 'Search', { fg = C.bg, bg = C.accent, bold = true })
hi(0, 'Comment', { fg = C.comment, italic = true })
hi(0, 'Title', { fg = C.fg, bold = true })
hi(0, 'Constant', { fg = C.accent })
hi(0, 'String', { fg = C.green })
hi(0, 'Number', { fg = C.yellow })
hi(0, 'Boolean', { fg = C.purple })
hi(0, 'Identifier', { fg = C.fg })
hi(0, 'Function', { fg = C.accent, bold = true })
hi(0, 'Statement', { fg = C.purple })
hi(0, 'Keyword', { fg = C.purple })
hi(0, 'Type', { fg = C.cyan })
hi(0, 'Special', { fg = C.red })
hi(0, 'Delimiter', { fg = C.dim })
hi(0, 'DiagnosticError', { fg = C.red })
hi(0, 'DiagnosticWarn', { fg = C.yellow })
hi(0, 'DiagnosticInfo', { fg = C.blue })
hi(0, 'DiagnosticHint', { fg = C.cyan })
hi(0, 'DiffAdd', { fg = C.green, bg = C.bg })
hi(0, 'DiffChange', { fg = C.yellow, bg = C.bg })
hi(0, 'DiffDelete', { fg = C.red, bg = C.bg })
hi(0, 'Directory', { fg = C.accent })
