return {
  dir = vim.fn.stdpath("config"),
  name = "pi-local",
  cmd = {
    "PiToggle",
    "PiChatToggle",
    "PiFocus",
    "PiChatFocus",
    "PiAsk",
    "PiInlineAsk",
    "PiAskSelection",
    "PiInlineAskSelection",
    "PiAddCurrentFile",
    "PiInlineAddCurrentFile",
    "PiAddPath",
    "PiInlineAddPath",
    "PiCancel",
    "PiInlineCancel",
    "PiLog",
    "PiModel",
    "PiModelReset",
    "PiSessionNew",
    "PiChatNew",
    "PiSessions",
    "PiInlineSessions",
    "PiResume",
    "PiChatResume",
    "PiContinue",
    "PiChatContinue",
    "PiCloseSession",
    "PiChatClose",
    "PiChatReview",
    "PiStatus",
    "PiDiffAccept",
    "PiInlineDiffAccept",
    "PiDiffDeny",
    "PiInlineDiffDeny",
    "PiDiffCascadeDeny",
    "PiInlineDiffCascadeDeny",
  },
  keys = {
    { "<leader>;", nil, desc = "AI/pi" },
    { "<leader>;c", "<cmd>PiChatToggle<cr>", desc = "pi chat: toggle" },
    { "<leader>;f", "<cmd>PiChatFocus<cr>", desc = "pi chat: focus" },
    { "<leader>;R", "<cmd>PiChatResume<cr>", desc = "pi chat: resume" },
    { "<leader>;C", "<cmd>PiChatContinue<cr>", desc = "pi chat: continue" },
    { "<leader>;n", "<cmd>PiChatNew<cr>", desc = "pi chat: new session" },
    { "<leader>;X", "<cmd>PiChatClose<cr>", desc = "pi chat: close session" },

    { "<leader>;i", "<cmd>PiInlineAsk<cr>", desc = "pi inline: ask" },
    { "<leader>;i", "<cmd>PiInlineAskSelection<cr>", mode = "v", desc = "pi inline: ask selection" },
    { "<leader>;b", "<cmd>PiInlineAddCurrentFile<cr>", desc = "pi inline: add current buffer" },
    { "<leader>;s", "<cmd>PiInlineAskSelection<cr>", mode = "v", desc = "pi inline: send selection" },
    {
      "<leader>;s",
      "<cmd>PiInlineAddPath<cr>",
      desc = "pi inline: add path",
      ft = { "neo-tree", "oil", "minifiles", "netrw" },
    },
    { "<leader>;a", "<cmd>PiInlineDiffAccept<cr>", desc = "pi inline: accept diff" },
    { "<leader>;d", "<cmd>PiInlineDiffDeny<cr>", desc = "pi inline: deny diff" },
    { "<leader>;r", "<cmd>PiInlineDiffDeny<cr>", desc = "pi inline: reject diff" },
    { "<leader>;D", "<cmd>PiInlineDiffCascadeDeny<cr>", desc = "pi inline: cascade reject diff" },
    { "<leader>;l", "<cmd>PiInlineSessions<cr>", desc = "pi inline: list sessions" },
    { "<leader>;x", "<cmd>PiInlineCancel<cr>", desc = "pi inline: cancel" },

    { "<leader>;m", "<cmd>PiModel<cr>", desc = "pi inline: select model" },
    { "<leader>;L", "<cmd>PiLog<cr>", desc = "pi: open log" },
  },
  config = function()
    require("pi_core").setup({
      rpc = {
        tools = true,
        skills = true,
        extensions = true,
      },
    })
  end,
}
