-- Shared semantic highlight specification for Intrace themes.
-- Variant modules provide role-based palettes; this module owns group coverage.

local M = {}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.apply(C)
  vim.o.termguicolors = true
  vim.o.background = C.background

  -- Core editor -----------------------------------------------------------
  hi("Normal",         { fg = C.fg, bg = C.bg })
  hi("NormalNC",       { fg = C.fg_soft, bg = C.bg })
  hi("NormalFloat",    { fg = C.fg, bg = C.surface })
  hi("FloatBorder",    { fg = C.brown_bright, bg = C.surface })
  hi("FloatTitle",     { fg = C.accent_bright, bg = C.surface, bold = true })
  hi("FloatFooter",    { fg = C.muted, bg = C.surface })
  hi("FloatShadow",    { bg = C.bg, blend = 80 })
  hi("FloatShadowThrough", { bg = C.bg, blend = 100 })
  hi("WinSeparator",   { fg = C.border_strong, bg = C.bg })
  hi("VertSplit",      { link = "WinSeparator" })
  hi("MsgSeparator",   { fg = C.border_strong, bg = C.surface })
  hi("WinBar",         { fg = C.fg, bg = C.surface, bold = true })
  hi("WinBarNC",       { fg = C.muted, bg = C.bg_alt })

  -- Editor chrome ---------------------------------------------------------
  hi("LineNr",         { fg = C.muted, bg = C.bg })
  hi("LineNrAbove",    { fg = C.muted, bg = C.bg })
  hi("LineNrBelow",    { fg = C.muted, bg = C.bg })
  hi("CursorLine",     { bg = C.surface_alt })
  hi("CursorColumn",   { bg = C.surface_alt })
  hi("CursorLineNr",   { fg = C.yellow_bright, bg = C.surface_alt, bold = true })
  hi("CursorLineFold", { fg = C.yellow_bright, bg = C.surface_alt })
  hi("CursorLineSign", { bg = C.surface_alt })
  hi("ColorColumn",    { bg = C.surface_alt })
  hi("SignColumn",     { bg = C.bg })
  hi("FoldColumn",     { fg = C.muted, bg = C.bg })
  hi("Folded",         { fg = C.muted, bg = C.surface })
  hi("Conceal",        { fg = C.muted })
  hi("SpecialKey",     { fg = C.punctuation })
  hi("Whitespace",     { fg = C.border })
  hi("NonText",        { fg = C.border })
  hi("EndOfBuffer",    { fg = C.bg, bg = C.bg })

  -- Statusline / tabline --------------------------------------------------
  hi("StatusLine",       { fg = C.fg, bg = C.surface })
  hi("StatusLineNC",     { fg = C.muted, bg = C.bg_alt })
  hi("StatusLineTerm",   { link = "StatusLine" })
  hi("StatusLineTermNC", { link = "StatusLineNC" })
  hi("TabLine",          { fg = C.muted, bg = C.bg_alt })
  hi("TabLineSel",       { fg = C.fg_bright, bg = C.surface, bold = true })
  hi("TabLineFill",      { bg = C.bg_alt })

  -- Popup menus -----------------------------------------------------------
  hi("Pmenu",         { fg = C.fg, bg = C.surface })
  hi("PmenuSel",      { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("PmenuKind",     { fg = C.cyan, bg = C.surface })
  hi("PmenuKindSel",  { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("PmenuExtra",    { fg = C.muted, bg = C.surface })
  hi("PmenuExtraSel", { fg = C.accent_fg, bg = C.accent })
  hi("PmenuSbar",     { bg = C.surface_alt })
  hi("PmenuThumb",    { bg = C.border_strong })
  hi("PmenuMatch",    { fg = C.accent_bright, bg = C.surface, bold = true })
  hi("PmenuMatchSel", { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("ComplMatchIns", { fg = C.accent_bright, bold = true })

  -- Selection / search ----------------------------------------------------
  hi("Visual",       { fg = C.selection_fg, bg = C.selection })
  hi("VisualNOS",    { fg = C.selection_fg, bg = C.selection })
  hi("Search",       { fg = C.search_fg, bg = C.search, bold = true })
  hi("IncSearch",    { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("CurSearch",    { fg = C.yellow_fg, bg = C.yellow_bright, bold = true })
  hi("Substitute",   { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("MatchParen",   { fg = C.cyan, bg = C.surface_alt, bold = true, underline = true })
  hi("QuickFixLine", { fg = C.selection_fg, bg = C.selection, bold = true })
  hi("WildMenu",     { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("SnippetTabstop", { bg = C.reference, underline = true, sp = C.cyan })

  -- Messages --------------------------------------------------------------
  hi("Comment",    { fg = C.comment, italic = true })
  hi("Todo",       { fg = C.todo_fg, bg = C.purple, bold = true })
  hi("Title",      { fg = C.fg_bright, bold = true })
  hi("WarningMsg", { fg = C.amber, bold = true })
  hi("ErrorMsg",   { fg = C.red, bold = true })
  hi("MoreMsg",    { fg = C.green_bright })
  hi("ModeMsg",    { fg = C.green_bright, bold = true })
  hi("Question",   { fg = C.green_bright, bold = true })
  hi("MsgArea",    { fg = C.fg, bg = C.bg })

  -- Spell: shape as well as color distinguishes each state. ---------------
  hi("SpellBad",   { undercurl = true, sp = C.red })
  hi("SpellCap",   { underdouble = true, sp = C.blue })
  hi("SpellRare",  { underdotted = true, sp = C.purple_bright })
  hi("SpellLocal", { underdashed = true, sp = C.cyan })

  -- Traditional syntax ----------------------------------------------------
  hi("Constant",      { fg = C.accent_soft })
  hi("String",        { fg = C.green })
  hi("Character",     { fg = C.green_bright })
  hi("Number",        { fg = C.yellow_bright })
  hi("Boolean",       { fg = C.purple_bright, bold = true })
  hi("Float",         { fg = C.yellow_bright })
  hi("Identifier",    { fg = C.fg_soft })
  hi("Function",      { fg = C.accent_text, bold = true })
  hi("Statement",     { fg = C.purple })
  hi("Conditional",   { fg = C.purple_bright, bold = true })
  hi("Repeat",        { fg = C.purple_bright })
  hi("Label",         { fg = C.purple })
  hi("Operator",      { fg = C.muted })
  hi("Keyword",       { fg = C.purple })
  hi("Exception",     { fg = C.red, bold = true })
  hi("PreProc",       { fg = C.accent_text })
  hi("Include",       { fg = C.purple })
  hi("Define",        { fg = C.accent_text })
  hi("Macro",         { fg = C.accent_text })
  hi("PreCondit",     { fg = C.purple })
  hi("Type",          { fg = C.cyan })
  hi("StorageClass",  { fg = C.cyan })
  hi("Structure",     { fg = C.cyan })
  hi("Typedef",       { fg = C.cyan })
  hi("Special",       { fg = C.accent_soft })
  hi("SpecialChar",   { fg = C.cyan })
  hi("Tag",           { fg = C.accent_soft })
  hi("Delimiter",     { fg = C.punctuation })
  hi("SpecialComment",{ fg = C.comment, bold = true })
  hi("Debug",         { fg = C.red })
  hi("Underlined",    { fg = C.blue, underline = true })
  hi("Ignore",        { fg = C.muted })
  hi("Error",         { fg = C.error_fg, bg = C.red, bold = true })

  -- Diagnostics -----------------------------------------------------------
  hi("DiagnosticError", { fg = C.red, bold = true })
  hi("DiagnosticWarn",  { fg = C.amber })
  hi("DiagnosticInfo",  { fg = C.blue })
  hi("DiagnosticHint",  { fg = C.hint })
  hi("DiagnosticOk",    { fg = C.green })
  hi("DiagnosticSignError", { fg = C.red, bold = true })
  hi("DiagnosticSignWarn",  { fg = C.amber, bold = true })
  hi("DiagnosticSignInfo",  { fg = C.blue })
  hi("DiagnosticSignHint",  { fg = C.hint })
  hi("DiagnosticSignOk",    { fg = C.green })
  hi("DiagnosticVirtualTextError", { fg = C.red, bold = true })
  hi("DiagnosticVirtualTextWarn",  { fg = C.amber })
  hi("DiagnosticVirtualTextInfo",  { fg = C.blue })
  hi("DiagnosticVirtualTextHint",  { fg = C.hint })
  hi("DiagnosticVirtualTextOk",    { fg = C.green })
  hi("DiagnosticUnderlineError", { undercurl = true, sp = C.red })
  hi("DiagnosticUnderlineWarn",  { underdouble = true, sp = C.amber })
  hi("DiagnosticUnderlineInfo",  { underdotted = true, sp = C.blue })
  hi("DiagnosticUnderlineHint",  { underdashed = true, sp = C.hint })
  hi("DiagnosticUnderlineOk",    { underline = true, sp = C.green })
  hi("DiagnosticDeprecated",     { strikethrough = true, sp = C.red })
  hi("LspInlayHint",             { fg = C.muted, italic = true })

  -- Reference highlights must remain visible even when semantic highlighting
  -- uses the same foreground as Normal.
  hi("LspReferenceText",  { bg = C.reference })
  hi("LspReferenceRead",  { bg = C.reference_r, underline = true, sp = C.cyan_dim })
  hi("LspReferenceWrite", { bg = C.reference_w, bold = true, underline = true, sp = C.accent_bright })
  hi("LspSignatureActiveParameter", { fg = C.fg_bright, bg = C.reference, bold = true })

  -- Diff / Git ------------------------------------------------------------
  hi("DiffAdd",    { fg = C.green_bright, bg = C.diff_add })
  hi("DiffChange", { fg = C.yellow_bright, bg = C.diff_change })
  hi("DiffDelete", { fg = C.accent_soft, bg = C.diff_delete })
  hi("DiffText",   { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("Added",      { fg = C.green_bright })
  hi("Changed",    { fg = C.yellow_bright })
  hi("Removed",    { fg = C.accent_soft })
  hi("diffAdded",     { fg = C.green_bright, bg = C.diff_add })
  hi("diffRemoved",   { fg = C.accent_soft, bg = C.diff_delete })
  hi("diffChanged",   { fg = C.yellow_bright, bg = C.diff_change })
  hi("diffLine",      { fg = C.blue, bg = C.surface })
  hi("diffFile",      { fg = C.muted })
  hi("diffOldFile",   { fg = C.accent_soft })
  hi("diffNewFile",   { fg = C.green_bright })
  hi("diffIndexLine", { fg = C.muted })
  hi("diffSubname",   { fg = C.cyan })
  hi("@diff.plus",  { fg = C.green_bright, bg = C.diff_add })
  hi("@diff.minus", { fg = C.accent_soft, bg = C.diff_delete })
  hi("@diff.delta", { fg = C.yellow_bright, bg = C.diff_change })
  hi("GitSignsAdd",              { fg = C.green })
  hi("GitSignsChange",           { fg = C.yellow })
  hi("GitSignsDelete",           { fg = C.red })
  hi("GitSignsCurrentLineBlame", { fg = C.muted, italic = true })

  -- Telescope -------------------------------------------------------------
  hi("TelescopeNormal",          { fg = C.fg, bg = C.surface })
  hi("TelescopeBorder",          { fg = C.border_strong, bg = C.surface })
  hi("TelescopeSelection",       { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("TelescopeMatching",        { fg = C.accent_bright, bold = true })
  hi("TelescopePromptPrefix",    { fg = C.accent })
  hi("TelescopePromptNormal",    { fg = C.fg, bg = C.surface })
  hi("TelescopePromptBorder",    { fg = C.border_strong, bg = C.surface })
  hi("TelescopePromptTitle",     { fg = C.accent_bright, bg = C.surface, bold = true })
  hi("TelescopeResultsNormal",   { fg = C.fg_soft, bg = C.surface })
  hi("TelescopeResultsBorder",   { fg = C.border_strong, bg = C.surface })
  hi("TelescopeResultsTitle",    { fg = C.cyan, bg = C.surface, bold = true })
  hi("TelescopePreviewNormal",   { fg = C.fg, bg = C.surface })
  hi("TelescopePreviewBorder",   { fg = C.border_strong, bg = C.surface })
  hi("TelescopePreviewTitle",    { fg = C.green_bright, bg = C.surface, bold = true })
  hi("TelescopeSelectionCaret",  { fg = C.accent_fg, bg = C.accent })
  hi("TelescopeMultiSelection",  { fg = C.cyan, bold = true })
  hi("TelescopeMultiIcon",       { fg = C.cyan })

  -- Blink.cmp -------------------------------------------------------------
  hi("BlinkCmpMenu",                       { fg = C.fg, bg = C.surface })
  hi("BlinkCmpMenuBorder",                 { fg = C.border_strong, bg = C.surface })
  hi("BlinkCmpMenuSelection",              { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("BlinkCmpLabel",                      { fg = C.fg })
  hi("BlinkCmpLabelMatch",                 { fg = C.accent_bright, bold = true })
  hi("BlinkCmpLabelDeprecated",            { fg = C.muted, strikethrough = true })
  hi("BlinkCmpLabelDetail",                { fg = C.muted })
  hi("BlinkCmpLabelDescription",           { fg = C.muted })
  hi("BlinkCmpSource",                     { fg = C.comment })
  hi("BlinkCmpKind",                       { fg = C.cyan })
  hi("BlinkCmpGhostText",                  { fg = C.muted, italic = true })
  hi("BlinkCmpDoc",                        { fg = C.fg, bg = C.surface })
  hi("BlinkCmpDocBorder",                  { fg = C.border_strong, bg = C.surface })
  hi("BlinkCmpDocSeparator",               { fg = C.border, bg = C.surface })
  hi("BlinkCmpDocCursorLine",              { bg = C.surface_alt })
  hi("BlinkCmpScrollBarThumb",             { bg = C.border_strong })
  hi("BlinkCmpScrollBarGutter",            { bg = C.surface_alt })
  hi("BlinkCmpSignatureHelp",              { fg = C.fg, bg = C.surface })
  hi("BlinkCmpSignatureHelpBorder",        { fg = C.border_strong, bg = C.surface })
  hi("BlinkCmpSignatureHelpActiveParameter", { fg = C.fg_bright, bg = C.reference, bold = true })

  -- nvim-cmp --------------------------------------------------------------
  hi("CmpItemAbbr",           { fg = C.fg })
  hi("CmpItemAbbrMatch",      { fg = C.accent_bright, bold = true })
  hi("CmpItemAbbrMatchFuzzy", { fg = C.accent_bright })
  hi("CmpItemAbbrDeprecated", { fg = C.muted, strikethrough = true })
  hi("CmpItemKind",           { fg = C.cyan })
  hi("CmpItemKindFunction",   { fg = C.accent_text })
  hi("CmpItemKindMethod",     { fg = C.accent_text })
  hi("CmpItemKindVariable",   { fg = C.cyan })
  hi("CmpItemKindKeyword",    { fg = C.purple_bright })
  hi("CmpItemMenu",           { fg = C.muted })

  -- NvimTree --------------------------------------------------------------
  hi("Directory",                    { fg = C.yellow_bright })
  hi("NvimTreeNormal",               { fg = C.fg, bg = C.bg })
  hi("NvimTreeNormalNC",             { fg = C.fg_soft, bg = C.bg })
  hi("NvimTreeNormalFloat",          { fg = C.fg, bg = C.surface })
  hi("NvimTreeNormalFloatBorder",    { fg = C.border_strong, bg = C.surface })
  hi("NvimTreeWinSeparator",         { fg = C.border_strong, bg = C.bg })
  hi("NvimTreeCursorLine",           { bg = C.surface_alt })
  hi("NvimTreeFolderName",           { fg = C.yellow_bright })
  hi("NvimTreeOpenedFolderName",     { fg = C.yellow_bright, bold = true })
  hi("NvimTreeRootFolder",           { fg = C.accent_bright, bold = true })
  hi("NvimTreeFolderIcon",           { fg = C.yellow })
  hi("NvimTreeOpenedFolderIcon",     { fg = C.yellow_bright })
  hi("NvimTreeIndentMarker",         { fg = C.border })
  hi("NvimTreeWindowPicker",         { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("NvimTreeGitDeletedIcon",       { fg = C.red })
  hi("NvimTreeGitDirtyIcon",         { fg = C.amber })
  hi("NvimTreeGitIgnoredIcon",       { fg = C.muted })
  hi("NvimTreeGitMergeIcon",         { fg = C.purple_bright })
  hi("NvimTreeGitNewIcon",           { fg = C.green })
  hi("NvimTreeGitRenamedIcon",       { fg = C.blue })
  hi("NvimTreeGitStagedIcon",        { fg = C.green_bright })

  -- lazy.nvim -------------------------------------------------------------
  hi("LazyNormal",       { fg = C.fg, bg = C.bg })
  hi("LazyButton",       { fg = C.fg_soft, bg = C.surface })
  hi("LazyButtonActive", { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("LazyH1",           { fg = C.accent_text, bold = true })
  hi("LazyProgressDone", { fg = C.green_bright })
  hi("LazyProgressTodo", { fg = C.border_strong })

  -- bufferline.nvim -------------------------------------------------------
  hi("BufferLineIndicatorSelected", { fg = C.accent })
  hi("BufferLineFill",              { bg = C.bg_alt })
  hi("BufferLineBackground",        { fg = C.muted, bg = C.bg })
  hi("BufferLineBufferSelected",    { fg = C.fg_bright, bg = C.bg, bold = true })
  hi("BufferLineBufferVisible",     { fg = C.fg_soft, bg = C.bg })
  hi("BufferLineSeparator",         { fg = C.border, bg = C.bg })
  hi("BufferLineSeparatorSelected", { fg = C.border_strong, bg = C.bg })

  -- mason.nvim ------------------------------------------------------------
  hi("MasonNormal",         { fg = C.fg, bg = C.bg })
  hi("MasonHeader",         { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("MasonHighlight",      { fg = C.cyan })
  hi("MasonHighlightBlock", { fg = C.bg, bg = C.cyan })
  hi("MasonMuted",          { fg = C.muted })
  hi("MasonError",          { fg = C.red })

  -- noice.nvim ------------------------------------------------------------
  hi("NoicePopup",              { fg = C.fg, bg = C.surface })
  hi("NoicePopupBorder",        { fg = C.border_strong, bg = C.surface })
  hi("NoiceCmdline",            { fg = C.fg, bg = C.bg })
  hi("NoiceCmdlineIcon",        { fg = C.accent_text })
  hi("NoiceCmdlinePopup",       { fg = C.fg, bg = C.surface })
  hi("NoiceCmdlinePopupBorder", { fg = C.border_strong, bg = C.surface })
  hi("NoiceConfirm",            { fg = C.fg, bg = C.surface })
  hi("NoiceConfirmBorder",      { fg = C.border_strong, bg = C.surface })

  -- Oil.nvim --------------------------------------------------------------
  hi("OilDir",               { fg = C.yellow_bright, bold = true })
  hi("OilDirIcon",           { fg = C.yellow })
  hi("OilFile",              { fg = C.fg })
  hi("OilFileHidden",        { fg = C.muted })
  hi("OilHidden",            { fg = C.muted })
  hi("OilSocket",            { fg = C.purple_bright })
  hi("OilLink",              { fg = C.cyan })
  hi("OilLinkTarget",        { fg = C.comment, italic = true })
  hi("OilOrphanLink",        { fg = C.red })
  hi("OilOrphanLinkTarget",  { fg = C.red, italic = true })
  hi("OilCopy",              { fg = C.cyan, bold = true })
  hi("OilMove",              { fg = C.amber, bold = true })
  hi("OilDelete",            { fg = C.red, bold = true })
  hi("OilCreate",            { fg = C.green, bold = true })
  hi("OilChange",            { fg = C.yellow_bright })
  hi("OilRestore",           { fg = C.green })
  hi("OilPurge",             { fg = C.red, bold = true })
  hi("OilTrash",             { fg = C.red })
  hi("OilTrashSourcePath",   { fg = C.comment, italic = true })
  hi("OilPermissionNone",    { fg = C.border_strong })
  hi("OilPermissionRead",    { fg = C.green })
  hi("OilPermissionWrite",   { fg = C.amber })
  hi("OilPermissionExecute", { fg = C.red })

  -- Trouble ---------------------------------------------------------------
  hi("TroubleNormal",    { fg = C.fg, bg = C.surface })
  hi("TroubleNormalNC",  { fg = C.fg_soft, bg = C.surface })
  hi("TroubleText",      { fg = C.fg })
  hi("TroubleFilename",  { fg = C.yellow_bright })
  hi("TroubleDirectory", { fg = C.comment })
  hi("TroubleSource",    { fg = C.comment, italic = true })
  hi("TroubleCode",      { fg = C.accent_soft })
  hi("TroublePos",       { fg = C.muted })
  hi("TroubleCount",     { fg = C.accent_fg, bg = C.accent, bold = true })
  hi("TroubleIndent",    { fg = C.border })
  hi("TroublePreview",   { fg = C.selection_fg, bg = C.selection })
  hi("TroubleIconError", { fg = C.red })
  hi("TroubleIconWarn",  { fg = C.amber })
  hi("TroubleIconHint",  { fg = C.hint })
  hi("TroubleIconInfo",  { fg = C.blue })

  -- Snacks notifier -------------------------------------------------------
  for _, level in ipairs({ "Info", "Warn", "Error", "Debug", "Trace" }) do
    local color = ({
      Info = C.blue,
      Warn = C.amber,
      Error = C.red,
      Debug = C.muted,
      Trace = C.muted,
    })[level]
    hi("SnacksNotifier" .. level,       { fg = C.fg, bg = C.surface })
    hi("SnacksNotifierIcon" .. level,   { fg = color, bg = C.surface })
    hi("SnacksNotifierBorder" .. level, { fg = color, bg = C.surface })
    hi("SnacksNotifierTitle" .. level,  { fg = color, bg = C.surface, bold = true })
    hi("SnacksNotifierFooter" .. level, { fg = color, bg = C.surface })
  end
  hi("SnacksNotifierMinimal",         { fg = C.fg, bg = C.surface })
  hi("SnacksNotifierHistory",         { fg = C.fg, bg = C.bg })
  hi("SnacksNotifierHistoryTitle",    { fg = C.fg_bright, bold = true })
  hi("SnacksNotifierHistoryDateTime", { fg = C.muted })

  -- render-markdown -------------------------------------------------------
  hi("RenderMarkdownH1",         { fg = C.purple_bright, bold = true })
  hi("RenderMarkdownH2",         { fg = C.cyan, bold = true })
  hi("RenderMarkdownH3",         { fg = C.amber, bold = true })
  hi("RenderMarkdownH4",         { fg = C.blue, bold = true })
  hi("RenderMarkdownH5",         { fg = C.accent_soft, bold = true })
  hi("RenderMarkdownH6",         { fg = C.purple })
  hi("RenderMarkdownCode",       { bg = C.surface })
  hi("RenderMarkdownCodeBorder", { bg = C.surface_alt })
  hi("RenderMarkdownCodeInfo",   { fg = C.comment, bg = C.surface })
  hi("RenderMarkdownCodeInline", { fg = C.accent_bright, bg = C.surface })
  hi("RenderMarkdownBullet",     { fg = C.accent_text })
  hi("RenderMarkdownDash",       { fg = C.border_strong })
  hi("RenderMarkdownLink",       { fg = C.blue, underline = true })
  hi("RenderMarkdownWikiLink",   { fg = C.cyan, underline = true })
  hi("RenderMarkdownQuote",      { fg = C.comment, italic = true })
  hi("RenderMarkdownMath",       { fg = C.purple_bright })
  hi("RenderMarkdownChecked",    { fg = C.green })
  hi("RenderMarkdownUnchecked",  { fg = C.muted })
  hi("RenderMarkdownTodo",       { fg = C.amber })
  hi("RenderMarkdownTableHead",  { fg = C.fg_bright, bold = true })
  hi("RenderMarkdownTableRow",   { fg = C.fg })
  hi("RenderMarkdownSuccess",    { fg = C.green })
  hi("RenderMarkdownInfo",       { fg = C.blue })
  hi("RenderMarkdownHint",       { fg = C.hint })
  hi("RenderMarkdownWarn",       { fg = C.amber })
  hi("RenderMarkdownError",      { fg = C.red })

  -- Rainbow delimiters ----------------------------------------------------
  hi("RainbowDelimiterRed",    { fg = C.accent_soft })
  hi("RainbowDelimiterYellow", { fg = C.yellow_bright })
  hi("RainbowDelimiterBlue",   { fg = C.blue })
  hi("RainbowDelimiterOrange", { fg = C.accent_text })
  hi("RainbowDelimiterGreen",  { fg = C.green })
  hi("RainbowDelimiterViolet", { fg = C.purple })
  hi("RainbowDelimiterCyan",   { fg = C.cyan })

  -- WhichKey (harmless when the plugin is absent) -------------------------
  hi("WhichKey",          { fg = C.purple_bright })
  hi("WhichKeyGroup",     { fg = C.accent_bright })
  hi("WhichKeyDesc",      { fg = C.fg })
  hi("WhichKeyNormal",    { fg = C.fg, bg = C.surface })
  hi("WhichKeySeparator", { fg = C.border_strong })
  hi("WhichKeyValue",     { fg = C.muted })

  -- UFO folds -------------------------------------------------------------
  hi("UfoFoldedFg",          { fg = C.fg_soft })
  hi("UfoFoldedBg",          { bg = C.surface })
  hi("UfoFoldedEllipsis",    { fg = C.comment, italic = true })
  hi("UfoCursorFoldedLine",  { bg = C.surface_alt, bold = true })
  hi("UfoPreviewSbar",       { bg = C.surface_alt })
  hi("UfoPreviewThumb",      { bg = C.border_strong })
  hi("UfoPreviewWinBar",     { fg = C.fg, bg = C.surface })
  hi("UfoPreviewCursorLine", { fg = C.selection_fg, bg = C.selection })

  -- DAP -------------------------------------------------------------------
  hi("DapBreakpoint",          { fg = C.red, bold = true })
  hi("DapBreakpointCondition", { fg = C.amber, bold = true })
  hi("DapBreakpointRejected",  { fg = C.muted })
  hi("DapLogPoint",            { fg = C.blue })
  hi("DapStopped",             { fg = C.green_bright, bg = C.reference_r, bold = true })
  hi("DapUINormal",            { fg = C.fg, bg = C.bg })
  hi("DapUIVariable",          { fg = C.fg_soft })
  hi("DapUIValue",             { fg = C.fg })
  hi("DapUIType",              { fg = C.cyan })
  hi("DapUIScope",             { fg = C.yellow_bright, bold = true })
  hi("DapUIThread",            { fg = C.fg_soft })
  hi("DapUIStoppedThread",     { fg = C.green, bold = true })
  hi("DapUIModifiedValue",     { fg = C.accent_bright, bold = true })
  hi("DapUIDecoration",        { fg = C.border_strong })
  hi("DapUIFloatNormal",       { fg = C.fg, bg = C.surface })
  hi("DapUIFloatBorder",       { fg = C.border_strong, bg = C.surface })
  hi("DapUIWatchesEmpty",      { fg = C.muted })
  hi("DapUIWatchesValue",      { fg = C.green })
  hi("DapUIWatchesError",      { fg = C.red })
  hi("DapUIBreakpointsInfo",   { fg = C.green })
  hi("DapUIBreakpointsPath",   { fg = C.blue })
  hi("DapUIBreakpointsCurrentLine", { fg = C.yellow_bright, bold = true })

  -- Indent guides ---------------------------------------------------------
  hi("IblIndent", { fg = C.border })
  hi("IblScope",  { fg = C.border_strong })

  -- Treesitter: generic captures -----------------------------------------
  hi("@variable",                   { fg = C.fg_soft })
  hi("@variable.builtin",           { fg = C.purple_bright })
  hi("@variable.parameter",         { fg = C.parameter })
  hi("@variable.parameter.builtin", { fg = C.accent_soft })
  hi("@variable.member",            { fg = C.fg_soft })
  hi("@constant",                   { fg = C.accent_soft })
  hi("@constant.builtin",           { fg = C.purple_bright })
  hi("@constant.macro",             { fg = C.accent_text })
  hi("@module",                     { fg = C.cyan })
  hi("@module.builtin",             { fg = C.purple_bright })
  hi("@label",                      { fg = C.purple })
  hi("@string",                     { fg = C.green })
  hi("@string.documentation",       { fg = C.docstring, italic = true })
  hi("@string.regexp",              { fg = C.accent_soft })
  hi("@string.escape",              { fg = C.cyan })
  hi("@string.special",             { fg = C.accent_bright })
  hi("@string.special.url",         { fg = C.blue, underline = true })
  hi("@character",                  { fg = C.green_bright })
  hi("@boolean",                    { fg = C.purple_bright, bold = true })
  hi("@number",                     { fg = C.yellow_bright })
  hi("@number.float",               { fg = C.yellow_bright })
  hi("@type",                       { fg = C.cyan })
  hi("@type.builtin",               { fg = C.cyan_dim })
  hi("@type.definition",            { fg = C.cyan })
  hi("@attribute",                  { fg = C.brown_bright, bold = true })
  hi("@attribute.builtin",          { fg = C.brown_bright, bold = true })
  hi("@property",                   { fg = C.fg_soft })
  hi("@function",                   { fg = C.accent_text, bold = true })
  hi("@function.builtin",           { fg = C.green_bright })
  hi("@function.call",              { fg = C.accent_text })
  hi("@function.method",            { fg = C.accent_text, bold = true })
  hi("@function.method.call",       { fg = C.accent_text })
  hi("@function.macro",             { fg = C.accent_text })
  hi("@constructor",                { fg = C.yellow_bright, bold = true })
  hi("@operator",                   { fg = C.muted })
  hi("@keyword",                    { fg = C.purple })
  hi("@keyword.function",           { fg = C.purple_bright, bold = true })
  hi("@keyword.type",               { fg = C.purple_bright })
  hi("@keyword.import",             { fg = C.purple })
  hi("@keyword.repeat",             { fg = C.purple_bright })
  hi("@keyword.conditional",        { fg = C.purple_bright, bold = true })
  hi("@keyword.exception",          { fg = C.red, bold = true })
  hi("@punctuation",                { fg = C.punctuation })
  hi("@punctuation.bracket",        { fg = C.punctuation })
  hi("@punctuation.delimiter",      { fg = C.punctuation })
  hi("@punctuation.special",        { fg = C.cyan })
  hi("@comment",                    { fg = C.comment, italic = true })
  hi("@comment.error",              { fg = C.red, bold = true })
  hi("@comment.warning",            { fg = C.amber, bold = true })
  hi("@comment.todo",               { fg = C.todo_fg, bg = C.purple, bold = true })
  hi("@comment.note",               { fg = C.blue, bold = true })
  hi("@markup.heading",             { fg = C.fg_bright, bold = true })
  hi("@markup.link",                { fg = C.blue, underline = true })
  hi("@markup.link.url",            { fg = C.blue, underline = true })
  hi("@markup.raw.block",           { bg = C.surface_alt })
  hi("@markup.quote",               { fg = C.comment, italic = true })

  -- Python-specific captures. Current nvim-treesitter uses @attribute for
  -- decorators and @punctuation.special for f-string interpolation braces.
  hi("@string.documentation.python", { fg = C.docstring, italic = true })
  hi("@function.builtin.python",     { fg = C.green_bright })
  hi("@variable.builtin.python",     { fg = C.purple_bright })
  hi("@constant.builtin.python",     { fg = C.purple_bright })
  hi("@keyword.function.python",     { fg = C.purple_bright, bold = true })
  hi("@keyword.type.python",         { fg = C.purple_bright, bold = true })
  hi("@function.python",             { fg = C.accent_text, bold = true })
  hi("@function.call.python",        { fg = C.accent_text })
  hi("@type.python",                 { fg = C.cyan })
  hi("@variable.parameter.python",   { fg = C.parameter })
  hi("@attribute.python",            { fg = C.brown_bright, bold = true })
  hi("@attribute.builtin.python",    { fg = C.brown_bright, bold = true })
  hi("@punctuation.special.python",  { fg = C.cyan })
  hi("@string.escape.python",        { fg = C.cyan })

  -- TypeScript / JavaScript ----------------------------------------------
  hi("@type.typescript",                 { fg = C.cyan })
  hi("@type.builtin.typescript",         { fg = C.cyan_dim })
  hi("@keyword.type.typescript",         { fg = C.purple_bright })
  hi("@constructor.typescript",          { fg = C.yellow_bright, bold = true })
  hi("@function.call.typescript",        { fg = C.accent_text })
  hi("@function.method.call.typescript", { fg = C.accent_text })

  -- LSP semantic tokens ---------------------------------------------------
  hi("@lsp.type.parameter",     { fg = C.parameter })
  hi("@lsp.type.variable",      { fg = C.fg_soft })
  hi("@lsp.type.property",      { fg = C.fg_soft })
  hi("@lsp.type.type",          { fg = C.cyan })
  hi("@lsp.type.class",         { fg = C.yellow_bright, bold = true })
  hi("@lsp.type.interface",     { fg = C.cyan, bold = true })
  hi("@lsp.type.struct",        { fg = C.cyan })
  hi("@lsp.type.enum",          { fg = C.yellow_bright, bold = true })
  hi("@lsp.type.enumMember",    { fg = C.accent_soft })
  hi("@lsp.type.typeParameter", { fg = C.parameter })
  hi("@lsp.type.decorator",     { fg = C.brown_bright, bold = true })
  hi("@lsp.type.function",      { fg = C.accent_text, bold = true })
  hi("@lsp.type.method",        { fg = C.accent_text, bold = true })
  hi("@lsp.type.namespace",     { fg = C.cyan })
  hi("@lsp.type.keyword",       { fg = C.purple })
  hi("@lsp.type.macro",         { fg = C.accent_text })
  hi("@lsp.type.number",        { fg = C.yellow_bright })
  hi("@lsp.type.operator",      { fg = C.muted })
  hi("@lsp.type.regexp",        { fg = C.accent_soft })
  hi("@lsp.type.string",        { fg = C.green })
  hi("@lsp.type.comment",       { fg = C.comment, italic = true })
  hi("@lsp.mod.deprecated",     { strikethrough = true, sp = C.red })

  -- Terminal ANSI palette -------------------------------------------------
  local terminal = {
    C.terminal_black, C.red, C.green, C.yellow, C.blue, C.purple, C.cyan, C.terminal_white,
    C.terminal_bright_black, C.accent_soft, C.green_bright, C.yellow_bright,
    C.blue, C.purple_bright, C.cyan, C.terminal_bright_white,
  }
  vim.g.terminal_ansi_colors = terminal
  for index, color in ipairs(terminal) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end
end

return M
